name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '59 23 28-31 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linux-gnu:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
     matrix:
        file_name:
          - qwer.txt
          - asdf.txt
          - zxcv.txt
       
    steps:
      - uses: actions/checkout@v4

      # Wait to close the issue: https://github.com/rust-lang/cargo/issues/12366
      - name: ${{matrix.file_name}}
        run: touch ${{matrix.file_name}}
                 
      - name: Upload Combined Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'artifact-${{matrix.file_name}}'
          path: ./combined_artifacts/${{matrix.file_name}}
          

